- name: Set solr_zk_host variable
  set_fact:
    solr_zk_host: "{{ zookeeper_nodes.keys() | join(',') }}"

- name: Configure solr.in.sh
  template:
    src: templates/solr.in.sh.j2
    dest: /etc/default/solr.in.sh
    owner: root
    group: solr
    mode: 0640
  notify: restart solr
